openapi: 3.0.1
info:
  title: angular-108-rest-server
  description: Rest server pour le cours Angular 108 by GC
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Examples
  description: Simple example endpoints
- name: Specification
  description: The swagger API specification
paths:
  /examples:
    get:
      tags:
      - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
          content: {}
    post:
      tags:
      - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        200:
          description: Returns all examples
          content: {}
  /examples/{id}:
    get:
      tags:
      - Examples
      parameters:
      - name: id
        in: path
        description: The id of the example to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}
  /lotb:
    get:
      tags:
      - Lotb
      description: Fetch all toons
      responses:
        200:
          description: Returns all toons
          content: {}
    post:
      tags:
      - Lotb
      description: Create a new toon
      requestBody:
        description: a toon
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToonBody'
        required: true
      responses:
        200:
          description: Returns all toons
          content: {}
  /lotb/{id}:
    get:
      tags:
      - Lotb
      description: Get a specific toon
      parameters:
      - name: id
        in: path
        description: The id of the toon to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the toon with the specified id
          content: {}
        404:
          description: Toon not found
          content: {}
    put:
      tags:
      - Lotb
      description: Update an existing toon
      parameters:
      - name: id
        in: path
        description: The id of the toon to retrieve
        required: true
        schema:
          type: string
      requestBody:
        description: a toon
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToonBody'
        required: true          
      responses:
        200:
          description: Return the toon with the specified id
          content: {}
        404:
          description: Toon not found
          content: {}
    delete:
      tags:
      - Lotb
      description: Delete an existing toon
      parameters:
      - name: id
        in: path
        description: The id of the toon to delete
        required: true
        schema:
          type: string
      responses:
        200:
          description: Deleted the toon with the specified id
          content: {}
        404:
          description: Toon not found
          content: {}                              
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    ExampleBody:
      title: example
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
    ToonBody:
      title: toon
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: eddie

